login/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('admin-login/', views.admin_login, name='admin_login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('todos-productos/', views.all_products, name='all_products'),
    path('enviar_correo/', views.enviar_correo, name='enviar_correo'),
    path('weather/', views.weather, name='weather'),
    path('product_detail/<str:prod_id>/', views.product_detail, name='product_detail'),
    path('favorites/', views.favorites, name='favorites'),
    path('like_product/<str:product_id>', views.like_product, name='like_product'),
    path('comprar/<str:prod_id>/', views.comprar_producto, name='comprar_producto'),
    path('confirmacion/', views.pagina_de_confirmacion, name='pagina_de_confirmacion'), 
    path('toggle_user_active/', views.toggle_user_active, name='toggle_user_active'),
    path('inactive/', views.inactive, name='inactive'),
    path('toggle_product_active/', views.toggle_product_active, name='toggle_product_active'),
    path('sold_products/', views.sold_products, name='sold_products'),
    path('rate_seller/<str:seller_id>', views.rate_seller, name='rate_seller'),
    path('products-cards/', views.products_cards_view, name='products-cards'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tindplace/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.urls import include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('login.urls')),
    path('eval/', include('evaluacion.urls')),
    path("", include('publicaciones.urls')),
]

login/models.py
from django.db import models


class Address(models.Model):
    comuna = models.ForeignKey('Comuna', models.DO_NOTHING)
    cod_postal = models.CharField(max_length=255, blank=True, null=True)
    casa_o_dep = models.IntegerField()
    calle = models.CharField(max_length=255)
    user = models.OneToOneField('User', on_delete=models.CASCADE)
    numero = models.CharField(max_length=255)
    comentario = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'address'
        app_label = 'login'


class Admin(models.Model):
    admin_id = models.CharField(primary_key=True, max_length=255)
    admin_name1 = models.CharField(max_length=255)
    admin_name2 = models.CharField(max_length=255, blank=True, null=True)
    admin_surname1 = models.CharField(max_length=255)
    admin_surname2 = models.CharField(max_length=255, blank=True, null=True)
    admin_email = models.CharField(max_length=255)
    admin_date_hire = models.DateField()
    admin_status = models.BooleanField()
    is_super_admin = models.BooleanField()

    class Meta:
        managed = False
        db_table = 'admin'


class Affinity(models.Model):
    af_id = models.IntegerField(primary_key=True)
    af_name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'affinity'

    def __str__(self):
        return self.af_name


class Category(models.Model):
    cat_id = models.IntegerField(primary_key=True)
    cat_name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'category'


class Comuna(models.Model):
    comuna_id = models.IntegerField(primary_key=True)
    provincia = models.ForeignKey('Provincia', models.DO_NOTHING)
    comuna_name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'comuna'


class Historical(models.Model):
    hist_id = models.IntegerField(primary_key=True)
    date = models.DateField()
    buyer_id = models.CharField(max_length=255)
    prod = models.ForeignKey('Product', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'historical'


class Indictment(models.Model):
    id_prod_indct = models.IntegerField(primary_key=True)
    report_date = models.DateField()
    user_reported = models.CharField(max_length=255)
    user_accuser = models.CharField(max_length=255)
    report_description = models.CharField(max_length=255)
    report_action = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'indictment'


class Match(models.Model):
    user = models.OneToOneField('User', on_delete=models.CASCADE)
    match_date = models.DateField()
    user_liked = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'match'


class Product(models.Model):
    prod_id = models.CharField(primary_key=True, max_length=255)
    prod_name = models.CharField(max_length=255)
    id_prod_indct = models.IntegerField()
    prod_new = models.BooleanField()
    permuta = models.BooleanField()
    prod_price = models.IntegerField()
    prod_date = models.DateField()
    prod_score = models.IntegerField(blank=True, null=True)
    prod_seller = models.ForeignKey('User', models.DO_NOTHING, db_column='prod_seller')
    prod_reported = models.BooleanField(null=True)
    prod_active = models.BooleanField()
    prod_description = models.CharField(max_length=255)
    prod_affinitie1 = models.IntegerField()
    prod_affinitie2 = models.IntegerField(blank=True, null=True)
    prod_photo1 = models.ImageField(upload_to='photos/', null=True, blank=True)
    prod_photo2 = models.ImageField(upload_to='photos/', null=True, blank=True)
    prod_photo3 = models.ImageField(upload_to='photos/', null=False, blank=True)
    prod_photo4 = models.ImageField(upload_to='photos/', null=False, blank=True)
    prod_photo5 = models.ImageField(upload_to='photos/', null=False, blank=True)

    class Meta:
        managed = False
        db_table = 'product'


class ProductCategory(models.Model):
    product = models.ForeignKey(
        Category, models.DO_NOTHING, db_column='product')
    category = models.ForeignKey(
        Product, models.DO_NOTHING, db_column='category')

    class Meta:
        managed = False
        db_table = 'product_category'


class ProductScore(models.Model):
    score_id = models.IntegerField(primary_key=True)
    user_reviewer = models.CharField(max_length=255)
    product_reviewed = models.ForeignKey(
        Product, models.DO_NOTHING, db_column='product_reviewed')
    score_date = models.DateField()
    score_value = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'product_score'


class Provincia(models.Model):
    provincia_id = models.IntegerField(primary_key=True)
    region = models.ForeignKey('Region', models.DO_NOTHING)
    provincia_name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'provincia'


class Region(models.Model):
    region_id = models.IntegerField(primary_key=True)
    region_name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'region'


class User(models.Model):
    user_id = models.CharField(primary_key=True, max_length=255)
    user_name1 = models.CharField(max_length=255)
    user_name2 = models.CharField(max_length=255, blank=True, null=True)
    user_surname1 = models.CharField(max_length=255)
    user_surname2 = models.CharField(max_length=255, blank=True, null=True)
    user_email = models.CharField(max_length=255)
    user_password = models.CharField(max_length=255)
    user_last_loc_lat = models.FloatField(blank=True, null=True)
    user_last_loc_long = models.FloatField(blank=True, null=True)
    user_date_lastloc = models.DateField(blank=True, null=True)
    date_registred = models.DateField()
    date_last_login = models.DateField()
    user_score = models.IntegerField()
    user_phone = models.IntegerField()
    user_active = models.BooleanField()
    user_inetrest1 = models.IntegerField()
    user_interest2 = models.IntegerField()
    user_photo = models.ImageField(upload_to='profile_photos/', null=True, blank=True)
    user_sells = models.IntegerField()
    user_is_premium = models.BooleanField()
    user_premium_start = models.DateField(blank=True, null=True)
    user_premium_ends = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'user'


class UserScore(models.Model):
    score_id = models.IntegerField(primary_key=True)
    user_reviwer = models.ForeignKey(
        User, models.DO_NOTHING, db_column='user_reviwer', blank=True, null=True)
    user_reviwed = models.CharField(max_length=255)
    score_date = models.DateField()
    score_value = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'user_score'


class Comment(models.Model):
    id_comment = models.AutoField(primary_key=True)
    product = models.ForeignKey('Product', models.DO_NOTHING)
    user = models.ForeignKey('User', models.DO_NOTHING)
    text = models.TextField()

    class Meta:
        managed = False
        db_table = 'comment'

# Productos Favoritos
class UserFavoriteProduct(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'product')
        db_table = 'user_favorite_product'

login/forms.py
from .models import Affinity, UserScore
from django import forms
from .models import Comment, User


class LoginForm(forms.Form):
    user_email = forms.EmailField(label='Email')
    user_password = forms.CharField(widget=forms.PasswordInput, label='Contraseña')

class RegistrationForm(forms.Form):
    user_id = forms.CharField(label='Rut', max_length=255)
    user_name1 = forms.CharField(label='Nombre', max_length=255)
    user_name2 = forms.CharField(label='Segundo nombre', max_length=255, required=False)
    user_surname1 = forms.CharField(label='Apellido', max_length=255)
    user_surname2 = forms.CharField(label='Segundo apellido', max_length=255, required=False)
    user_email = forms.EmailField(label='Correo electrónico', max_length=255)
    user_password = forms.CharField(label='Contraseña', max_length=255, widget=forms.PasswordInput)
    user_phone = forms.IntegerField(label='Teléfono')
    user_inetrest1 = forms.ModelChoiceField(
        label='Interés 1',
        queryset=Affinity.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    user_interest2 = forms.ModelChoiceField(
        label='Interés 2',
        queryset=Affinity.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    user_photo = forms.ImageField(label='Foto', required=False)

class AdminForm(forms.Form):
    admin_email = forms.CharField(max_length=255)
    admin_name1 = forms.CharField(max_length=255)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class UserScoreForm(forms.ModelForm):
    class Meta:
        model = UserScore
        fields = ['user_reviwed', 'score_value']

login/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Tindplace</title>
    <link rel="icon" type="image/x-icon" href="{% static 'tind-icon.svg' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!--Boostrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous" />
    <!--Tipografía Google-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap"
        rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">



</head>

<body style="font-family: 'Open Sans', sans-serif">
    {% include 'nav.html' %}

    {% block content %}
    {% endblock %}


    <style>
        .hidden {
            display: none;
        }
    </style>
    <!-- Modal Favorite-->
    <!-- Modal cuando se hace click para agregar a fatoritos: -->
    <div class="modal fade " id="customModal" tabindex="-1" aria-labelledby="customModalLabel" aria-hidden="true">
        <div class="modal-dialog ">
            <div class="modal-content border-0">
                <div class="d-flex justify-content-center align-items-center flex-column">
                    <div class="bg-white d-flex align-items-center  flex-column overflow-hidden"
                        style="border-radius: 20px;">
                        <div class=" overflow-hidden">
                            <img class="" style="width: 300px;"
                                src="https://cdn.dribbble.com/users/2070959/screenshots/5881187/copy_2.gif" alt="">
                        </div>
                        <div class="modal-body" id="customModalBody">
                            Contenido del modal
                        </div>
                        <div class=" pb-3">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                            <a name="" id="" class="btn btn-danger" href="{% url 'favorites' %}" role="button">Ver mis
                                fav <svg width="13" height="12" viewBox="0 0 13 12" fill="none"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M9.45455 0.5C8.21364 0.5 7.12045 1.14167 6.5 2.15C5.87955 1.14167 4.78636 0.5 3.54545 0.5C1.59545 0.5 0 2.15 0 4.16667C0 7.80278 6.5 11.5 6.5 11.5C6.5 11.5 13 7.83333 13 4.16667C13 2.15 11.4045 0.5 9.45455 0.5Z"
                                        fill="white" />
                                </svg></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>




    {% if not hide_footer %}
    <footer class="position-fixed my-2" style="left: 0;bottom: 0;">
        <a class="tind-nav-btn nav-link ms-2 bg-light-subtle d-flex align-items-center p-3 shadow-sm" href="{% url 'evaluation' %}"> 
            Nos Gustaria saber tu opinion 
            <i class="fas fa-heart"></i>
            <i class="fas fa-heart"></i>
            <i class="fas fa-heart"></i>
        </a>
    </footer>
    {% endif %}

    <!--Boostrap JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>


</body>

</html>

login/templates/inactive.html
{% extends 'base.html' %}

{% block content %}
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Cuenta Inactiva</h5>
                        <p class="card-text">Lo sentimos, tu cuenta ha sido desactivada. Si crees que esto es un error o
                            deseas reactivar tu cuenta, por favor, contáctate con nuestro equipo de soporte.</p>
                        <a href="mailto:support@tindplace.com" class="btn btn-primary">Contactar Soporte</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

login/templates/product_detail.html
<!-- Aquí es donde renderizas los detalles de cada producto -->
{% load humanize %}

<div class="row">
    <div class="col-12 col-md-6 d-flex align-items-center">
        <div id="carouselExample" class="carousel slide w-100 tind-modal-r-content">
            <div class="carousel-inner">
                {% if product.prod_photo1 %}
                <div class="carousel-item active">
                    <img src="{{ product.prod_photo1.url }}" class="d-block w-100 card-img-top"
                        alt="{{ product.prod_name }}" onerror="imgError(this);">
                </div>
                {% else %}
                <div class="carousel-item w-100 position-relative d-flex align-items-center bg-light justify-content-center"
                    style="height: 238px;">
                    <svg height="60" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg" class="me-3">
                        <path
                            d="M28 1.414L26.586 0L0 26.586L1.414 28L3.414 26H24C24.5302 25.9992 25.0384 25.7882 25.4133 25.4133C25.7882 25.0384 25.9992 24.5302 26 24V3.414L28 1.414ZM24 24H5.414L13.207 16.207L15.586 18.586C15.9611 18.9609 16.4697 19.1716 17 19.1716C17.5303 19.1716 18.0389 18.9609 18.414 18.586L20 17L24 20.997V24ZM24 18.168L21.414 15.582C21.0389 15.2071 20.5303 14.9964 20 14.9964C19.4697 14.9964 18.9611 15.2071 18.586 15.582L17 17.168L14.623 14.791L24 5.414V18.168ZM4 20V17L9 12.003L10.373 13.377L11.789 11.961L10.414 10.586C10.0389 10.2111 9.53033 10.0004 9 10.0004C8.46967 10.0004 7.96106 10.2111 7.586 10.586L4 14.172V4H20V2H4C3.46973 2.00053 2.96133 2.21141 2.58637 2.58637C2.21141 2.96133 2.00053 3.46973 2 4V20H4Z"
                            fill="black" />
                    </svg>
                    <p class="m-0">
                        <b>¡Ups!</b> al parecer este producto<br> <i>no tiene imagen</i>
                    </p>
                </div>
                {% endif %}
                {% if product.prod_photo2 %}
                <div class="carousel-item">
                    <img src="{{ product.prod_photo2.url }}" class="d-block w-100 card-img-top"
                        alt="{{ product.prod_name }}" onerror="imgError(this);">
                </div>
                {% else %}
                <div class="carousel-item w-100 position-relative d-flex align-items-center p-3 bg-light justify-content-center"
                    style="height: 238px;">
                    <svg height="60" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg" class="me-3">
                        <path
                            d="M28 1.414L26.586 0L0 26.586L1.414 28L3.414 26H24C24.5302 25.9992 25.0384 25.7882 25.4133 25.4133C25.7882 25.0384 25.9992 24.5302 26 24V3.414L28 1.414ZM24 24H5.414L13.207 16.207L15.586 18.586C15.9611 18.9609 16.4697 19.1716 17 19.1716C17.5303 19.1716 18.0389 18.9609 18.414 18.586L20 17L24 20.997V24ZM24 18.168L21.414 15.582C21.0389 15.2071 20.5303 14.9964 20 14.9964C19.4697 14.9964 18.9611 15.2071 18.586 15.582L17 17.168L14.623 14.791L24 5.414V18.168ZM4 20V17L9 12.003L10.373 13.377L11.789 11.961L10.414 10.586C10.0389 10.2111 9.53033 10.0004 9 10.0004C8.46967 10.0004 7.96106 10.2111 7.586 10.586L4 14.172V4H20V2H4C3.46973 2.00053 2.96133 2.21141 2.58637 2.58637C2.21141 2.96133 2.00053 3.46973 2 4V20H4Z"
                            fill="black" />
                    </svg>
                    <p class="m-0">
                        <b>¡Ups!</b> al parecer este producto<br> <i>no tiene imagen</i>
                    </p>
                </div>
                {% endif %}
                {% if product.prod_photo3 %}
                <div class="carousel-item">
                    <img src="{{ product.prod_photo3.url }}" class="d-block w-100 card-img-top"
                        alt="{{ product.prod_name }}" onerror="imgError(this);">
                </div>
                {% else %}
                <div class="carousel-item w-100 position-relative d-flex align-items-center p-3 bg-light justify-content-center"
                    style="height: 238px;">
                    <svg height="60" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg" class="me-3">
                        <path
                            d="M28 1.414L26.586 0L0 26.586L1.414 28L3.414 26H24C24.5302 25.9992 25.0384 25.7882 25.4133 25.4133C25.7882 25.0384 25.9992 24.5302 26 24V3.414L28 1.414ZM24 24H5.414L13.207 16.207L15.586 18.586C15.9611 18.9609 16.4697 19.1716 17 19.1716C17.5303 19.1716 18.0389 18.9609 18.414 18.586L20 17L24 20.997V24ZM24 18.168L21.414 15.582C21.0389 15.2071 20.5303 14.9964 20 14.9964C19.4697 14.9964 18.9611 15.2071 18.586 15.582L17 17.168L14.623 14.791L24 5.414V18.168ZM4 20V17L9 12.003L10.373 13.377L11.789 11.961L10.414 10.586C10.0389 10.2111 9.53033 10.0004 9 10.0004C8.46967 10.0004 7.96106 10.2111 7.586 10.586L4 14.172V4H20V2H4C3.46973 2.00053 2.96133 2.21141 2.58637 2.58637C2.21141 2.96133 2.00053 3.46973 2 4V20H4Z"
                            fill="black" />
                    </svg>
                    <p class="m-0">
                        <b>¡Ups!</b> al parecer este producto<br> <i>no tiene imagen</i>
                    </p>
                </div>
                {% endif %}
                <!-- Continuar para las restantes imágenes (prod_photo3, prod_photo4, etc.) -->
            </div>

            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
    <div class="col-12 col-md-6 bg-white tind-modal-r-content p-4">
        <div class="row">
            <div class="col">
                <p class="tind-modal-title">Nombre del producto: {{ product.prod_name }}</p>
                <p class="tind-modal-price">Precio : {{ product.prod_price| intcomma }}</p>
            </div>
            <div class="col-2 d-flex justify-content-center align-items-center ">
                {% include 'btn-like.html' %}
            </div>

        </div>
        <div>

            <p>Descripción : {{ product.prod_description }}</p>
            <p>Vendedor : {{ product.prod_seller.user_name1 }} {{ product.prod_seller.user_surname1 }}</p>
        </div>

        <div class="row">
            <h4 class="text-black-50"> Comentarios : </h4>
            {% for comment in comments %}
            <div class="col-6">

                <div class="mb-3 shadow p-3 rounded">
                    <div class="card-body">
                        <div class="d-flex flex-start align-items-start">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" fill="currentColor"
                                class="bi bi-person-circle shadow-1-strong me-3" viewBox="0 0 16 16">
                                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                                <path fill-rule="evenodd"
                                    d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                            </svg>
                            <div class="w-100">
                                <div class="d-flex justify-content-between align-items-center ">
                                    <h6 class="fw-bold mb-0 text-body-tertiary">
                                        {{ comment.user.user_name1 }} {{ comment.user.user_surname1}}
                                        <span style="color:#F5487F;">{{ comment.text }}</span>
                                    </h6>
                                    <!-- <p class="mb-0">2 days ago</p> -->
                                </div>
                                <div class="d-flex justify-content-between align-items-center">
                                    <p class="small mb-0" style="color: #aaa;">
                                        <a href="#!" class="link-grey text-black-50 text-decoration-none">Remove</a> •
                                        <a href="#!" class="link-grey text-black-50  text-decoration-none">Reply</a>
                                    </p>
                                    <div class="d-flex flex-row">
                                        <i class="fas fa-star text-warning me-2"></i>
                                        <i class="far fa-check-circle" style="color: #aaa;"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>



            {% empty %}
            <p>No hay comentarios para este producto aún.</p>
            {% endfor %}
        </div>
        <h5>Añade un comentario</h5>
        <form method="post" id="formId" action="{% url 'product_detail' product.prod_id %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_text">Comentario:</label>
                <textarea id="id_text" name="text" class="form-control"
                    required>{{ form.text.value|default:'' }}</textarea>
                {{ form.text.errors }}
            </div>
            <button class="btn btn-light w-100" type="submit">Enviar comentario</button>
        </form>


        <div class="row mt-5">
            <div class="d-flex justify-content-around">
                <a href="{% url 'comprar_producto' prod_id=product.prod_id  %} " button class="btn btn-primary col-5"> <b>¡Ahora si!</b> Lo
                    quiero</a>
                <button type="button" class="btn btn-outline-secondary col-5" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<script>
    function imgError(image) {
        image.onerror = "";
        image.src = "";
        let svg = '<svg  height="60" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg" class="me-3"><path d="M28 1.414L26.586 0L0 26.586L1.414 28L3.414 26H24C24.5302 25.9992 25.0384 25.7882 25.4133 25.4133C25.7882 25.0384 25.9992 24.5302 26 24V3.414L28 1.414ZM24 24H5.414L13.207 16.207L15.586 18.586C15.9611 18.9609 16.4697 19.1716 17 19.1716C17.5303 19.1716 18.0389 18.9609 18.414 18.586L20 17L24 20.997V24ZM24 18.168L21.414 15.582C21.0389 15.2071 20.5303 14.9964 20 14.9964C19.4697 14.9964 18.9611 15.2071 18.586 15.582L17 17.168L14.623 14.791L24 5.414V18.168ZM4 20V17L9 12.003L10.373 13.377L11.789 11.961L10.414 10.586C10.0389 10.2111 9.53033 10.0004 9 10.0004C8.46967 10.0004 7.96106 10.2111 7.586 10.586L4 14.172V4H20V2H4C3.46973 2.00053 2.96133 2.21141 2.58637 2.58637C2.21141 2.96133 2.00053 3.46973 2 4V20H4Z" fill="black" /></svg>';
        image.outerHTML = '<div class="w-100 position-relative d-flex align-items-center p-3 bg-light justify-content-center" style="height: 238px;">' + svg + '<p class="m-0"><b>¡Ups!</b> al parecer este producto<br> <i>no tiene imagen</i></p></div>';
        return true;
    }

    $('#formId').on('submit', function (event) {
        event.preventDefault();  // Prevent form from being submitted

        $.ajax({
            url: $(this).attr('action'),  // Get the action URL from the form
            type: $(this).attr('method'),  // Get the method from the form
            data: $(this).serialize(),  // Serialize the form data for the POST request
            success: function (response) {
                if (response === 'Success') {
                    // Si el comentario se guardó con éxito, redirige a 'all_products.html' y muestra un mensaje de éxito
                    window.location.href = '/todos-productos';
                    alert('¡Su comentario fue enviado con éxito!');
                } else {
                    alert('Hubo un error al enviar tu comentario. Por favor inténtalo de nuevo.');
                }
            }
        });
    });


</script>